version: 2

sphinx:
  configuration: doc/source/conf.py

formats: all

build:
  image: latest

conda:
  environment: docs/source/environment.yml

python:
    version: 3
    install:
        - method: pip
          path: .
