language: python
python:
  # We don't actually use the Travis Python, but this keeps it organized.
  - "3.7"
  - "3.8"
  - "3.9"
install:
  - sudo apt update
  # We do this conditionally because it saves us some downloading if the
  # version is the same.
  - wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
  - bash miniconda.sh -b -p $HOME/miniconda
  - source "$HOME/miniconda/etc/profile.d/conda.sh"
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda
  # Useful for debugging any issues with conda
  - conda info -a

  # Replace dep1 dep2 ... with your dependencies
  - conda config --add channels conda-forge
  - conda create -q -n test-environment python=$TRAVIS_PYTHON_VERSION pytest numpy scipy coveralls pytest-cov Cython h5py mpi4py MEAutility gxx_linux-64 pip
  - conda activate test-environment
  # most tests should run even without NEURON/LFPy
  - if [[ "$TRAVIS_PYTHON_VERSION" < "3.9" ]]; then pip install neuron
  - if [[ "$TRAVIS_PYTHON_VERSION" < "3.9" ]]; then pip install git+https://github.com/LFPy/LFPy.git@2.2.dev0#egg=LFPy
  - if [[ "$TRAVIS_PYTHON_VERSION" < "3.9" ]]; then pip uninstall lfpykit -y  # uninstall LFPykit from LFPy installation before reinstall
  - python setup.py install

script:
  - bash .travisci/test_script.sh
after_success:
  - coveralls
