name: lfpykit
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3
  - numpy
  - matplotlib
  - jupyter
  - pip
  pip:
    - pip install ..
    - -e git+https://github.com/LFPy/LFPy.git@master#egg=LFPy
