# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Coveralls

on:
  pull_request:
    branches: [ master ]
  pull_request_target:
    types: [ opened, edited ]
    branches: [ master ]

jobs:
  build:

    runs-on: ${{ matrix.os }}
    strategy:
        matrix:
            os: [ubuntu-latest]
            python-version: [3.8]

    steps:
    - uses: actions/checkout@v2
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
    - name: Set up Python 3
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pytest wheel coverage pytest-cov coveralls
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
        if [[ "${{ matrix.python-version }}" < "3.9" ]]; then pip install neuron; fi
        pip install .
    - name: Test with pytest and coveralls
      env:
        COVERALLS_REPO_TOKEN: ${{ secrets.COVERALLS_REPO_TOKEN }}
      run: |
        py.test -v --cov=lfpykit/tests/
        coveralls
